store/urls.py
from store.forms import LoginForm, PasswordChangeForm, PasswordResetForm, SetPasswordForm
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views
from .views import SearchView

app_name = 'store'


urlpatterns = [
    path('', views.home, name="home"),
    path('search/', SearchView.as_view(), name='search'),
    # URL for Cart and Checkout
    path('add-to-cart/', views.add_to_cart, name="add-to-cart"),
    path('remove-cart/<int:cart_id>/', views.remove_cart, name="remove-cart"),
    path('plus-cart/<int:cart_id>/', views.plus_cart, name="plus-cart"),
    path('minus-cart/<int:cart_id>/', views.minus_cart, name="minus-cart"),
    path('add-notifi-like-home/', views.add_notifi_like_home, name="add-notifi-like-home"),
    path('add-notifi-like-cp/', views.add_notifi_like_cp, name="add-notifi-like-cp"),
    path('add-notifi-like-p/', views.add_notifi_like_p, name="add-notifi-like-p"),
    path('add-notifi-like-rp/', views.add_notifi_like_rp, name="add-notifi-like-rp"),
    path('introduce/', views.introduce, name="introduce"),
    path('cart/', views.cart, name="cart"),
    path('checkout/', views.checkout, name="checkout"),
    path('checkout-test/', views.checkout_test, name="checkout-test"),
    path('orders/', views.orders, name="orders"),
    path('billing/', views.billing, name="billing"),
    path('purchase-orders/', views.purchase_orders, name="purchase-orders"),
    path('invoice/', views.invoice, name="invoice"),
    path('like-products/', views.like_products, name="like-products"),
    path('remove-like/<int:favorite_id>/', views.remove_like, name="remove-like"),
    #URL for Products
    path('product/<slug:slug>/', views.detail, name="product-detail"),
    path('categories/', views.all_categories, name="all-categories"),
    path('<slug:slug>/', views.category_products, name="category-products"),

    path('shop/', views.shop, name="shop"),

    # URL for Authentication
    path('accounts/register/', views.RegistrationView.as_view(), name="register"),
    path('accounts/login/', auth_views.LoginView.as_view(template_name='account/login.html', authentication_form=LoginForm), name="login"),
    path('accounts/profile/', views.profile, name="profile"),
    path('accounts/add-address/', views.AddressView.as_view(), name="add-address"),
    path('accounts/remove-address/<int:id>/', views.remove_address, name="remove-address"),
    path('accounts/logout/', auth_views.LogoutView.as_view(next_page='store:login'), name="logout"),

    path('accounts/password-change/', auth_views.PasswordChangeView.as_view(template_name='account/password_change.html', form_class=PasswordChangeForm, success_url='/accounts/password-change-done/'), name="password-change"),
    path('accounts/password-change-done/', auth_views.PasswordChangeDoneView.as_view(template_name='account/password_change_done.html'), name="password-change-done"),

    path('accounts/password-reset/', auth_views.PasswordResetView.as_view(template_name='account/password_reset.html', form_class=PasswordResetForm, success_url='/accounts/password-reset/done/'), name="password-reset"), # Passing Success URL to Override default URL, also created password_reset_email.html due to error from our app_name in URL
    path('accounts/password-reset/done/', auth_views.PasswordResetDoneView.as_view(template_name='account/password_reset_done.html'), name="password_reset_done"),
    path('accounts/password-reset-confirm/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name='account/password_reset_confirm.html', form_class=SetPasswordForm, success_url='/accounts/password-reset-complete/'), name="password_reset_confirm"), # Passing Success URL to Override default URL
    path('accounts/password-reset-complete/', auth_views.PasswordResetCompleteView.as_view(template_name='account/password_reset_complete.html'), name="password_reset_complete"),

    path('product/test/', views.test, name="test"),

    
]

tikishop/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('store.urls')),
]

# To display images
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/base.html
{% load static %}

<!DOCTYPE html>
<html>

<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <title>{% block metatitle %}Tiến Thọ{% endblock metatitle %}</title>
  <meta name="description" content="">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="robots" content="all,follow">

  <script src="https://kit.fontawesome.com/1147679ae7.js" crossorigin="anomymous"></script>

  <link rel="stylesheet" href="{% static 'css/style.footer.css' %}">
  <!-- Bootstrap CSS-->
  <link rel="stylesheet" href="{% static 'vendor/bootstrap/css/bootstrap.min.css' %}">
  <!-- Lightbox-->
  <link rel="stylesheet" href="{% static 'vendor/lightbox2/css/lightbox.min.css' %}">
  <!-- Range slider-->
  <link rel="stylesheet" href="{% static 'vendor/nouislider/nouislider.min.css' %}">
  <!-- Bootstrap select-->
  <link rel="stylesheet" href="{% static 'vendor/bootstrap-select/css/bootstrap-select.min.css' %}">
  <!-- Owl Carousel-->
  <link rel="stylesheet" href="{% static 'vendor/owl.carousel2/assets/owl.carousel.min.css' %}">
  <link rel="stylesheet" href="{% static 'vendor/owl.carousel2/assets/owl.theme.default.css' %}">
  <!-- Google fonts-->
  <link rel="stylesheet"
    href="https://fonts.googleapis.com/css2?family=Libre+Franklin:wght@300;400;700&amp;display=swap">
  <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Martel+Sans:wght@300;400;800&amp;display=swap">
  <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Noto+Sans:ital,wght@0,100..900;1,100..900&display=swap">
  <!-- theme stylesheet-->
  <link rel="stylesheet" href="{% static 'css/style.default.css' %}" id="theme-stylesheet">
  <!-- Custom stylesheet - for your changes-->
  <link rel="stylesheet" href="{% static 'css/custom.css' %}">
  <!-- Favicon-->
  <link rel="shortcut icon" type="image/png" href="{% static 'img/logo.webp' %}">
  <!-- Tweaks for older IEs--><!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
        <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script><![endif]-->
</head>

<body>
  <div class="page-holder">
    {% include 'navbar.html' %}

    {% block content %}

    {% endblock content %}

    {% block payment-gateway %}{% endblock payment-gateway %}

    {% include 'footer.html' %}
    {% include 'scripts.html' %}
</body>


</html>

templates/footer.html
{% load static %}
<div class="bg-dark" style="height: 2px;">

</div>
<footer class="text-white " style=" background-color: white">
        <div class="container py-4">

          
            
          
          </section>
          <!-- /*----------------------------app---------------------------------*/ -->
          <section class="app-container">
            <p class="text-center" style="font-size: 17px;">Tải ứng dụng Tiến Thọ</p>
            <div class="app-google">
              <a href="https://www.apple.com/app-store/"><img  src="{% static 'img/appstore.jpg' %} "></a>
              <a href="https://play.google.com/"><img src="{% static 'img/googleplay.jpg' %} "></a>
              
            </div>
            
          </section>
          
          <!-- /*---------------------------footer------------------------*/ -->
          <div class="footer-top text-dark" style="font-size:11px;">
            <li><a href="#"><img src="{% static 'img/dathongbao.png' %}" alt=""></a></li>
            <li><a href="#">Liên hệ</a></li>
            <li><a href="#">Tuyển dụng</a></li>
            <li><a href="{% url 'store:introduce' %}">Giới thiệu</a></li>
            <li>
              <a href="https://www.facebook.com/" class="fab fa-facebook-f"></a>
              <a href="https://twitter.com/" class="fab fa-twitter"></a>
              <a href="https://www.youtube.com/" class="fab fa-youtube"></a>
            </li>
          </div>
          <div id="TD" class="footer-center text-dark" style="font-size: 11px;">
            <p>
              Công ty Cổ phần VinGroup với số đăng ký kinh doanh: 0123456789<br>
              Địa chỉ đăng ký: 334 Nguyễn Trãi, Thanh Xuân Trung, Thanh Xuân, Hà Nội, Việt Nam - 024 9999 6666<br>
              Đặt hàng online : <b>024 9999 6666</b> .
            </p>
          
          </div>
          <div class="footer-bottom text-dark" style="font-size: 11px;">
            ©TienTho All rights reserved
          </div>

        </div>
      </footer>

templates/navbar.html
{% load static %}
{% load humanize %}

<!-- navbar-->
<div class="d-flex flex-column justify-content-center align-items-center">
  <img src="{% static 'img/logo.webp' %}" alt="logo" height="200" width="300" class="img-fluid" />
  <header class="header w-100" style="background-color: #1a94ff;">

    <div class="container px-0 px-lg-0">

      <nav class="navbar navbar-expand-lg navbar-light py-3 px-lg-0" style=" font-family:'Noto Sans',sans-serif ;">
        <a href="{% url 'store:home' %}" class="active text-white">
          <span class="font-weight-bold text-white" style="font-size: 30px; margin-right: 20px;">Tiến Thọ</span></a>
        <a class="navbar-brand">
          <form class="form-inline my-2 my-lg-0" method="GET" action="{% url 'store:search' %}">
            <input class="form-control" action="" style="width: 300px;font-size: 13.5px; border: none" method="GET"
              type="text" placeholder="Tìm kiếm ..." aria-label="Search" name="query" value="{{ request.GET.query }}">
            <button class="btn justify-content-center" style="background-color: white;color: #1a94ff;border-left-color: #1a94ff;font-size: 13.5px ; " type="submit"><i
                class="fa fa-search"></i></button>
          </form>
          <!-- <span class="font-weight-bold text-white">Tiki</span></a> -->
          <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse"
            data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false"
            aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
          <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
              <li class="nav-item">
                <a class="nav-link active text-white" href="{% url 'store:home' %}"> Trang chủ</a>
              </li>
              <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle text-white" id="pagesDropdown" href="#" data-toggle="dropdown"
                  aria-haspopup="true" aria-expanded="false">
                  Danh mục</a>
                <div class="dropdown-menu mt-3" aria-labelledby="pagesDropdown">
                  {% if categories_menu %}
                  {% for cat_menu in categories_menu %}
                  <a class="dropdown-item border-0 transition-link"
                    href="{% url 'store:category-products' cat_menu.slug %}">{{cat_menu.title}}</a>
                  {% endfor %}
                  {% endif %}
                  <hr>
                  <a class="dropdown-item border-0 transition-link" href="{% url 'store:all-categories'  %}">Tất cả danh
                    mục</a>

            </ul>
            <ul class="navbar-nav ml-auto">
              {% if request.user.is_authenticated %}
              <li class="nav-item"><a class="nav-link my text-white" style="font-size: 15px;"
                  href="{% url 'store:cart' %}"> <i class="fas fa-dolly-flatbed mr-1 text-white"></i>Giỏ hàng<small
                    class="text-white">({{cart_items.count}})</small></a></li>

              <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle text-white" id="pagesDropdown" data-toggle="dropdown"
                  aria-haspopup="true" aria-expanded="false" style="font-size: 15px;" href="#">
                  <i class="far fa-bell mr-1"> </i>Thông báo
                </a>

                <div class="dropdown-menu mt-3" style="position: absolute;" aria-labelledby="pagesDropdown">
                  <a class="dropdown-item border-0 transition-link" href="#" style="font-size: 20px;">Thông báo</a>
                  <hr style="margin-top: 0; margin-bottom: 10px;">

                  {% if notification_list %}
                  {% if length == 0 %}
                  <p class="dropdown-item border-0 transition-link" style="font-size: 10px; ">Bạn chưa có thông báo.</p>
                  {% endif %}
                  {% for notification in notification_list %}
                  {% if notification.type == 1%}
                  <a class="dropdown-item  border-0 transition-link" style="font-size: 10px;text-wrap: wrap; word-wrap: break-word;"
                    href="{% url 'store:product-detail' notification.slug %}">
                    {{notification.content}}
                  </a>
                  <p style="margin-right: 15px; text-align: right; font-size: 10px; text-wrap: wrap; word-wrap: break-word;" class="small text-muted mb-0 ">
                    {{notification.date_added|naturaltime}}</p>
                  {% else %}
                  <a class="dropdown-item border-0 transition-link" style="font-size: 10px;text-wrap: wrap; word-wrap: break-word;"
                    href="{% url 'store:orders' %}">
                    {{notification.content}}
                  </a>
                  <p style="margin-right: 15px; text-align: right; font-size: 10px; text-wrap: wrap; word-wrap: break-word;" class="small text-muted mb-0">
                    {{notification.date_added|naturaltime}}</p>
                  {% endif %}
                  {% endfor %}

                  {% endif %}
              </li>

              {% comment %} <li class="nav-item">
                <a class="nav-link" href="#">
                  <i class="fas fa-user-alt mr-1"></i>
                  Tài khoản của tôi
                </a>
              </li> {% endcomment %}

              <li class="nav-item dropdown"><a class="nav-link dropdown-toggle
                   text-white" style="font-size: 15px;" id="pagesDropdown" href="#" data-toggle="dropdown"
                  aria-haspopup="true" aria-expanded="false"><i class="fas fa-user-alt mr-1 text-white"></i>Tài
                  khoản</a>
        </a>
        <div class="dropdown-menu mt-3" aria-labelledby="pagesDropdown">

          <a class="dropdown-item border-0 transition-link" href="{% url 'store:profile' %}">Tài khoản</a>
          <a class="dropdown-item border-0 transition-link" href="{% url 'store:like-products' %}">Sản phẩm ưu thích</a>
          <a class="dropdown-item border-0 transition-link" href="{% url 'store:cart' %}">Giỏ hàng</a>
          <a class="dropdown-item border-0 transition-link" href="{% url 'store:orders' %}">Đơn hàng</a>
          <a class="dropdown-item border-0 transition-link" href="{% url 'store:invoice' %}">Hoá đơn</a>
          <a class="dropdown-item border-0 transition-link" href="{% url 'store:purchase-orders' %}">Đơn đã mua</a>
          <a class="dropdown-item border-0 transition-link" href="{% url 'store:password-change' %}">Đổi mật khẩu</a>

          <hr>
          <a class="dropdown-item border-0 transition-link" href="{% url 'store:logout' %}">Đăng xuất</a>

          </li>
          {% else %}
          <li class="nav-item"><a class="nav-link text-white" style="font-size: 15px;"
              href="{% url 'store:login' %}">Đăng
              nhập</a></li>
          <li class="nav-item"><a class="nav-link text-white" style="font-size: 15px;"
              href="{% url 'store:register' %}">Tạo tài khoản</a></li>
          {% endif %}
          </ul>
        </div>
      </nav>
    </div>
  </header>
</div>

templates/scripts.html
{% load static %}

<!-- JavaScript files-->
      <script src="{% static 'vendor/jquery/jquery.min.js' %}"></script>
      <script src="{% static 'vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
      <script src="{% static 'vendor/lightbox2/js/lightbox.min.js' %}"></script>
      <script src="{% static 'vendor/nouislider/nouislider.min.js' %}"></script>
      <script src="{% static 'vendor/bootstrap-select/js/bootstrap-select.min.js' %}"></script>
      <script src="{% static 'vendor/owl.carousel2/owl.carousel.min.js' %}"></script>
      <script src="{% static 'vendor/owl.carousel2.thumbs/owl.carousel2.thumbs.min.js' %}"></script>
      <script src="{% static 'js/front.js' %}"></script>

      <script>
        var range = document.getElementById('range');
        noUiSlider.create(range, {
            range: {
                'min': 0,
                'max': 2000
            },
            step: 5,
            start: [100, 1000],
            margin: 300,
            connect: true,
            direction: 'ltr',
            orientation: 'horizontal',
            behaviour: 'tap-drag',
            tooltips: true,
            format: {
              to: function ( value ) {
                return '$' + value;
              },
              from: function ( value ) {
                return value.replace('', '');
              }
            }
        });
        
      </script>

      
      <script>
        // ------------------------------------------------------- //
        //   Inject SVG Sprite - 
        //   see more here 
        //   https://css-tricks.com/ajaxing-svg-sprite/
        // ------------------------------------------------------ //
        function injectSvgSprite(path) {
        
            var ajax = new XMLHttpRequest();
            ajax.open("GET", path, true);
            ajax.send();
            ajax.onload = function(e) {
            var div = document.createElement("div");
            div.className = 'd-none';
            div.innerHTML = ajax.responseText;
            document.body.insertBefore(div, document.body.childNodes[0]);
            }
        }
        // this is set to BootstrapTemple website as you cannot 
        // inject local SVG sprite (using only 'icons/orion-svg-sprite.svg' path)
        // while using file:// protocol
        // pls don't forget to change to your domain :)
        injectSvgSprite('https://bootstraptemple.com/files/icons/orion-svg-sprite.svg'); 
        
      </script>
      <!-- FontAwesome CSS - loading as last, so it doesn't block rendering-->
      <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.1/css/all.css" integrity="sha384-fnmOCqbTlWIlj8LyTjo7mOUStjsKC4pOpQbqyi7RrhN7udi9RwhKkMHpvLbHG9Sr" crossorigin="anonymous">
    </div>
  </body>
</html>