store/urls.py
from store.forms import LoginForm, PasswordChangeForm, PasswordResetForm, SetPasswordForm
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views
from .views import SearchView

app_name = 'store'


urlpatterns = [
    path('', views.home, name="home"),
    path('search/', SearchView.as_view(), name='search'),
    # URL for Cart and Checkout
    path('add-to-cart/', views.add_to_cart, name="add-to-cart"),
    path('remove-cart/<int:cart_id>/', views.remove_cart, name="remove-cart"),
    path('plus-cart/<int:cart_id>/', views.plus_cart, name="plus-cart"),
    path('minus-cart/<int:cart_id>/', views.minus_cart, name="minus-cart"),
    path('add-notifi-like-home/', views.add_notifi_like_home, name="add-notifi-like-home"),
    path('add-notifi-like-cp/', views.add_notifi_like_cp, name="add-notifi-like-cp"),
    path('add-notifi-like-p/', views.add_notifi_like_p, name="add-notifi-like-p"),
    path('add-notifi-like-rp/', views.add_notifi_like_rp, name="add-notifi-like-rp"),
    path('introduce/', views.introduce, name="introduce"),
    path('cart/', views.cart, name="cart"),
    path('checkout/', views.checkout, name="checkout"),
    path('checkout-test/', views.checkout_test, name="checkout-test"),
    path('orders/', views.orders, name="orders"),
    path('billing/', views.billing, name="billing"),
    path('purchase-orders/', views.purchase_orders, name="purchase-orders"),
    path('invoice/', views.invoice, name="invoice"),
    path('like-products/', views.like_products, name="like-products"),
    path('remove-like/<int:favorite_id>/', views.remove_like, name="remove-like"),
    #URL for Products
    path('product/<slug:slug>/', views.detail, name="product-detail"),
    path('categories/', views.all_categories, name="all-categories"),
    path('<slug:slug>/', views.category_products, name="category-products"),

    path('shop/', views.shop, name="shop"),

    # URL for Authentication
    path('accounts/register/', views.RegistrationView.as_view(), name="register"),
    path('accounts/login/', auth_views.LoginView.as_view(template_name='account/login.html', authentication_form=LoginForm), name="login"),
    path('accounts/profile/', views.profile, name="profile"),
    path('accounts/add-address/', views.AddressView.as_view(), name="add-address"),
    path('accounts/remove-address/<int:id>/', views.remove_address, name="remove-address"),
    path('accounts/logout/', auth_views.LogoutView.as_view(next_page='store:login'), name="logout"),

    path('accounts/password-change/', auth_views.PasswordChangeView.as_view(template_name='account/password_change.html', form_class=PasswordChangeForm, success_url='/accounts/password-change-done/'), name="password-change"),
    path('accounts/password-change-done/', auth_views.PasswordChangeDoneView.as_view(template_name='account/password_change_done.html'), name="password-change-done"),

    path('accounts/password-reset/', auth_views.PasswordResetView.as_view(template_name='account/password_reset.html', form_class=PasswordResetForm, success_url='/accounts/password-reset/done/'), name="password-reset"), # Passing Success URL to Override default URL, also created password_reset_email.html due to error from our app_name in URL
    path('accounts/password-reset/done/', auth_views.PasswordResetDoneView.as_view(template_name='account/password_reset_done.html'), name="password_reset_done"),
    path('accounts/password-reset-confirm/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name='account/password_reset_confirm.html', form_class=SetPasswordForm, success_url='/accounts/password-reset-complete/'), name="password_reset_confirm"), # Passing Success URL to Override default URL
    path('accounts/password-reset-complete/', auth_views.PasswordResetCompleteView.as_view(template_name='account/password_reset_complete.html'), name="password_reset_complete"),

    path('product/test/', views.test, name="test"),

    
]

tikishop/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('store.urls')),
]

# To display images
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

store/views.py
from multiprocessing import context
import string
import django
from django.contrib.auth.models import User
from store.models import Address, Cart, Category, Lastseen_Product, Notification, Order, Product,Comment,Profile,ProductReview,Favorite,Invoice,Voucher,UserVoucher
from django.shortcuts import redirect, render, get_object_or_404
from .forms import LoginForm, RegistrationForm, AddressForm,CommentForm,ProfileForm,RatingForm
from django.contrib import messages
from django.views import View
import decimal
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator # for Class Based Views
from django.db.models import Q,F
from django.views.generic import ListView
from datetime import datetime
from django.db.models import Avg
from django.core.paginator import EmptyPage, Paginator
from django.db.models import Q

def home(request):
    user = request.user
    categories = Category.objects.filter(is_active=True, is_featured=True).order_by('-count')[:4]
    products = Product.objects.filter(is_active=True, is_featured=True)[:8]
    products_popular = Product.objects.all().order_by('-count')[:8]
    all_categories = Category.objects.all()
    all_product = Product.objects.all() 
    all_products = []
    count_item_show = 8
    for category in all_categories:
        i = 0
        for product in all_product:
            if i < count_item_show and product.category == category:
                all_products.append(product)
                i+=1

    # all_products = Product.objects.all() 
    gmail = request.GET.get('gmail', '')    
    if (gmail):
        messages.success(request, "Đăng kí nhận thông báo vào gmail thành công!")
    context = {
        'categories': categories,
        'products': products,
        'products_popular':products_popular,
        'all_categories': all_categories,
        'all_products': all_products,
    }
    if request.user.is_authenticated:
        lastseen= Lastseen_Product.objects.filter(user=request.user).order_by('-created_at')[:4]
        lastseen_products = []
        for i in lastseen:
            lastseen_products.append(i.product)
        context['lastseen_products'] = lastseen_products
    return render(request, 'store/index.html', context)


def detail(request, slug):
    user = request.user
    product = get_object_or_404(Product, slug=slug)
    Product.objects.filter(slug=slug).update(count = F('count')+1)  # category count view +1
    Category.objects.filter(title=product.category.title).update(count = F('count')+1) #categor count view +1
    related_products = Product.objects.exclude(id=product.id).filter(is_active=True, category=product.category)[:8]
    form = CommentForm(instance=product)
    form1 =  RatingForm(instance=product)
    avg = ProductReview.objects.filter(product=product).aggregate(Avg('review_rating'))
    count_buy = Order.objects.filter(product = product,status='Delivered').count()
    checklike = None
    # them lastseen_product
    if request.user.is_authenticated:
        if(Lastseen_Product.objects.filter(user=user,product=product).exists()):
            Lastseen_Product.objects.get(user=user,product=product).delete()        
        Lastseen_Product(user=user,product=product).save()
    # them lastseen_product
    if request.user.is_authenticated:
        checklike = Favorite.objects.filter(user=user,product=product)
    context = {
        'form': form,
        'form1': form1,
        'product': product,
        'related_products': related_products,
        'avg':avg,
        'checklike':checklike,
        'count':count_buy,
    }
    if request.method == 'POST':
        form = CommentForm(request.POST, instance=product)
        form1 = RatingForm(request.POST, instance=product)
        if form.is_valid():
            name = request.user.username
            body = form.cleaned_data['content']
            c = Comment(product=product,user = user, commenter_name=name, comment_body=body, date_added=datetime.now())
            c.save()          
        elif form1.is_valid():
            if(not Order.objects.filter(user=user,product=product).exists()):
                messages.error(request, "Bạn không được đánh giá vì chưa mua hàng")
                form1 = RatingForm()
            else:
                review_text = form1.cleaned_data['review_text']
                review_rating = form1.cleaned_data['review_rating']
                if(ProductReview.objects.filter(user=user,product=product).exists()):
                    c =  ProductReview.objects.get(user =user,product=product)
                    c.review_text=review_text
                    c.review_rating = review_rating
                    c.save()
                else:
                    c = ProductReview(user = user,product=product,review_text=review_text,review_rating=review_rating)
                    c.save()
                avg = ProductReview.objects.filter(product=product).aggregate(Avg('review_rating'))
                context['avg']=avg
    else:
        form = CommentForm()    
        form1 = RatingForm()

    return render(request, 'store/detail.html', context)


def all_categories(request):
    categories = Category.objects.filter(is_active=True)
    return render(request, 'store/categories.html', {'categories':categories})

def introduce(request):
    return render(request, 'store/introduce.html')


def price__range(min_price,max_price):
    
    product=Product.objects.price < max_price and Product.objects.price > min_price

    return product

def category_products(request, slug):
    category = get_object_or_404(Category, slug=slug)
    products = Product.objects.filter(is_active=True, category=category)    
    categories = Category.objects.filter(is_active=True)
    filter_price = request.GET.get('filter_price', '')
    sorting = request.GET.get('sorting', '')
    min_price=0
    max_price=99999999999
    # Lọc theo giá
    if filter_price !='':
        if filter_price == '1':
                min_price=0
                max_price=100000
        if filter_price == '2':
                min_price=100000
                max_price=200000
        if filter_price == '3':
                min_price=200000
                max_price=400000
        if filter_price == '4':
                min_price=400000
                max_price=1000000
        if filter_price == '5':
                min_price=1000000        
        products = Product.objects.filter(is_active=True, category=category,price__lte=max_price,price__gte=min_price).order_by('-price')
        context = {
            'type':1,
            'category': category,
            'all':products,
            'products': products,
            'categories': categories,
            'filter_price': filter_price,
        }   
        return render(request, 'store/category_products.html', context) 
    # Sắp xếp
    if sorting != '':        
        if sorting == "high-low":
            products = Product.objects.filter(is_active=True, category=category,price__lte=max_price,price__gte=min_price).order_by('-price')
        if sorting == "low-high":
            products = Product.objects.filter(is_active=True, category=category,price__lte=max_price,price__gte=min_price).order_by('-price').reverse()
            # products = reversed(list(Product.objects.filter(is_active=True, category=category,price__lte=max_price,price__gte=min_price).order_by('-price')))
        if sorting == "popularity":
            products = list(Product.objects.filter(is_active=True, category=category,price__lte=max_price,price__gte=min_price))
            count = [None]*len(products)
            i=0
            for product in products:
                count[i] = Order.objects.filter(product = product).count()
                i=i+1
            n = len(count)
            i=0
            for i in range(n-1):
                for j in range(0, n-i-1):
                    if count[j] < count[j + 1] :
                        count[j], count[j + 1] = count[j + 1], count[j]
                        products[j], products[j + 1] = products[j + 1], products[j]
        context = {
            'type':1,
            'category': category,
            'all':products,
            'products': products,
            'categories': categories,
            'sorting' : sorting,
        }
        return render(request, 'store/category_products.html', context)
    # Product     
    p = Paginator(products, 9)
    page_num = request.GET.get('page',1)
    try:
        page = p.page(page_num)
    except EmptyPage:
        page = p.page(1)
    context = {
        'type':0,
        'all':products,
        'category': category,
        'products': page,
        'categories': categories,
    }   
    return render(request, 'store/category_products.html', context)



# Authentication Starts Here

class RegistrationView(View):
    def get(self, request):
        form = RegistrationForm()
        return render(request, 'account/register.html', {'form': form})
    
    def post(self, request):
        form = RegistrationForm(request.POST)
        if form.is_valid():
            messages.success(request, "Bạn đã đăng ký tài khoản thành công")
            form.save()
            return redirect('store:login')
        return render(request, 'account/register.html', {'form': form})

@login_required
def profile(request):
    addresses = Address.objects.filter(user=request.user)
    orders = Order.objects.filter(user=request.user).order_by('-ordered_date')
    order = ['Pending', 'Accepted', 'Packed','On The Way','Delivered','Cancelled']
    order = {key: i for i, key in enumerate(order)}
    ordered_sections = sorted(orders, key=lambda orders: order.get(orders.status, 0))
    profile = request.user.profile
    form = ProfileForm(instance=profile)
    if request.method == 'POST':
        form = ProfileForm(request.POST, request.FILES,instance=profile)
        if form.is_valid():
            form.save()

templates/store/cart.html
{% extends 'base.html' %}
{% load static %}
{% load humanize %}

    {% block content %}
      <div class="container">
        <!-- HERO SECTION-->
        <section class="py-5 bg-light">
          <div class="container">
            <div class="row px-4 px-lg-5 py-lg-4 align-items-center">
              <div class="col-lg-6">
                <h1 class="h2 text-uppercase mb-0">Giỏ hàng</h1>
              </div>
              <div class="col-lg-6 text-lg-right">
                <nav aria-label="breadcrumb">
                  <ol class="breadcrumb justify-content-lg-end mb-0 px-0">
                    <li class="breadcrumb-item"><a href="{% url 'store:home' %}">Trang chủ</a></li>
                    <li class="breadcrumb-item active" aria-current="page">Giỏ hàng</li>
                  </ol>
                </nav>
              </div>
            </div>
          </div>
        </section>

        {% if cart_products %}
        <section class="py-5">
          <h2 class="h5 text-uppercase mb-4">Giỏ hàng</h2>

          {% include 'partials/_messages.html' %}

          <div class="row">
            <div class="col-lg-8 mb-4 mb-lg-0">
              <!-- CART TABLE-->
              <div class="table-responsive mb-4">
                <table class="table">
                  <thead class="bg-light">
                    <tr>
                      <th class="border-0" scope="col"> <strong class="text-small text-uppercase">Sản phẩm</strong></th>
                      <th class="border-0" scope="col"> <strong class="text-small text-uppercase">Giá</strong></th>
                      <th class="border-0" scope="col"> <strong class="text-small text-uppercase">Số lượng</strong></th>
                      <th class="border-0" scope="col"> <strong class="text-small text-uppercase">Tổng</strong></th>
                      <th class="border-0" scope="col"> </th>
                    </tr>
                  </thead>
                  <tbody>

                    {% for cart_product in cart_products %}
                    <tr>
                      <th class="pl-0 border-0" scope="row">
                        <div class="media align-items-center">

                          {% if cart_product.product.product_image %}
                            <a class="reset-anchor d-block animsition-link" href="{% url 'store:product-detail' cart_product.product.slug %}"><img src="{{cart_product.product.product_image.url}}" alt="{{cart_product.product.title}}" width="70"/></a>
                          {% else %}
                            <a class="reset-anchor d-block animsition-link" href="{% url 'store:product-detail' cart_product.product.slug %}"><img src="{% static 'img/product-detail-3.jpg' %}" alt="{{cart_product.product.title}}" width="70"/></a>
                          {% endif %}

                          <div class="media-body ml-3"><strong class="h6"><a class="reset-anchor animsition-link" href="{% url 'store:product-detail' cart_product.product.slug %}">{{cart_product.product.title}}</a></strong></div>
                        </div>
                      </th>
                      <td class="align-middle border-0">
                        <p class="mb-0 small">{{cart_product.product.price|floatformat:0}} đ</p>
                      </td>
                      <td class="align-middle border-0">
                        <div class="border d-flex align-items-center justify-content-between px-3"><span class="small text-uppercase text-gray headings-font-family">SL   </span>
                          <div class="quantity">
                            <a href="{% url 'store:minus-cart' cart_product.id %}" class="dec-btn p-0 ml-2"><i class="fas fa-minus"></i></a>
                            {% comment %} <button class="dec-btn p-0"><i class="fas fa-caret-left"></i></button> {% endcomment %}
                            <input class="form-control form-control-sm border-0 shadow-0 p-0" type="text" value="{{cart_product.quantity}}"/>
                            {% comment %} <button class="inc-btn p-0"><i class="fas fa-caret-right"></i></button> {% endcomment %}
                            <a href="{% url 'store:plus-cart' cart_product.id %}" class="inc-btn p-0"><i class="fas fa-plus"></i></a>
                          </div>
                        </div>
                      </td>
                      <td class="align-middle border-0">
                        <p class="mb-0 small">{{cart_product.total_price|floatformat:0}} đ</p>
                      </td>
                      <td class="align-middle border-0"><a class="reset-anchor" href="{% url 'store:remove-cart' cart_product.id %}"><i class="fas fa-trash-alt small text-muted"></i></a></td>
                    </tr>
                    {% endfor %}

                  </tbody>
                </table>
              </div>
              <!-- CART NAV-->
              <div class="bg-light px-4 py-3">
                <div class="row align-items-center text-center">
                  <div class="col-md-6 mb-3 mb-md-0 text-md-left"><a  style="font-size: 15px" class="btn btn-link p-0 text-dark btn-sm" href="{% url 'store:home' %}"><i class="fas fa-long-arrow-alt-left mr-2"> </i>Tiếp tục mua sắm</a></div>
                  <div class="col-md-6 text-md-right">
                  <form action="{% url 'store:checkout-test' %}" id="myform">
                          
                          <input type="hidden" name="total_amount"  value="{{total_amount}}">
                          <input type="hidden" name="voucher"  value="{{voucher}}">
                    <button style="border: none" type="submit" class="col-md-6 text-md-right bg-light" style="font-size: 12px"type="submit"> Thanh toán <i class="fas fa-long-arrow-alt-right mr-2"></i></button>

                  </form>
                </div>
                </div>
              </div>
            </div>
            <!-- ORDER TOTAL-->
            <div class="col-lg-4">
              <div class="card border-0 rounded-0 p-lg-4 bg-light">
                <div class="card-body">
                  <h5 class="text-uppercase mb-4">Tổng cộng</h5>
                  <ul class="list-unstyled mb-0">
                    <li class="d-flex align-items-center justify-content-between"><strong class="text-uppercase small font-weight-bold">Tổng hàng</strong><span class="text-muted small">{{amount|floatformat:0}} đ</span></li>
                    <li class="d-flex align-items-center justify-content-between"><strong class="text-uppercase small font-weight-bold">Phí giao hàng</strong><span class="text-muted small">+ {{shipping_amount}} đ</span></li>
                    <li class="border-bottom my-2"></li>
                    <li class="d-flex align-items-center justify-content-between mb-4"><strong class="text-uppercase small font-weight-bold">Tổng</strong><span>{{total_amount|floatformat:0}} đ</span></li>
                    <!-- <li>

                      <div class="input-group flex-column flex-sm-row mb-3">
                        <input class="form-control form-control-lg py-3" type="email" placeholder="Nhập email của bạn để nhận thông báo"
                          aria-describedby="button-addon2" name="gmail">
                        <div class="input-group-append">
                        </div>
                    </li> -->
                    <li>

                     <form action="#" >
                        <div class="form-group mb-0">
                          <input class="form-control" type="text" placeholder="Nhập mã giảm giá" name="voucher">
                          <button class="btn btn-white btn-sm btn-block" type="submit"> <i class="fas fa-gift mr-2"></i>Sử dụng </button>
                        </div>
                      </form> 

                    </li>
                  </ul>

                  
                  <h5 class="text-uppercase my-5" style="font-size: 15px">Chọn địa chỉ giao hàng</h5>
                  
                  <form action="{% url 'store:checkout' %}" id="myform">

                    {% if addresses %}
                      {% for address in addresses %}
                        <div class="mb-3">
                          <input type="hidden" name="total_amount"  value="{{total_amount}}">
                          <input type="hidden" name="voucher"  value="{{voucher}}">
                        <input type="radio" name="address" style="font-size: 10px;" value="{{address.id}}"> <strong>Địa chỉ {{forloop.counter}}</strong> <br>
                         {{address.locality}}, {{address.city}}, {{address.state}} 
                        </div>
                      {% endfor %}
                      
                      {%if addresses|length > 0 %}
                        <button type="submit" class="btn btn-dark btn-lg btn-outline-dark" style="font-size: 12px"type="submit"> <i class="fas fa-dollar-sign mr-2"></i>Thanh toán khi giao hàng</button>
                      
                      {% endif %}
                    {% endif %}

                    <!-- Set up a container element for the button -->
                    <div class="text-end" id="paypal-button-container"></div>

                    {% comment %} For Cash on Delivery {% endcomment %}

                  </form>

                </div>
              </div>
            </div>

          </div>
        </section>
        
        {% else %}

          <div class="text-center py-5">
            <h3 class="mb-3">Giỏ hàng còn trống.</h3>
            <a href="{% url 'store:home' %}"><i class="fas fa-long-arrow-alt-left mr-2"> </i>Tiếp tục mau sắm</a>
          </div>

        {% endif %}

      </div>
      {% endblock content %}

      {% block payment-gateway %}
        <!-- Include the PayPal JavaScript SDK -->
    <script src="https://www.paypal.com/sdk/js?client-id=YOUR-PAYPAL-CLIENT-ID&currency=USD"></script>

    <script>
        // Render the PayPal button into #paypal-button-container
        paypal.Buttons({

            // Set up the transaction
            createOrder: function(data, actions) {
                return actions.order.create({
                    purchase_units: [{
                        amount: {
                            value: '{{total_amount}}'
                        }
                    }]
                });
            },

            // Finalize the transaction
            onApprove: function(data, actions) {
                return actions.order.capture().then(function(details) {
                    // Show a success message to the buyer
                    alert('Transaction completed by ' + details.payer.name.given_name + '!');
                    // Savind Order in Database after Payment Success
                    document.getElementById('myform').submit();
                });
            }


        }).render('#paypal-button-container');
    </script>
      {% endblock payment-gateway %}

templates/store/like_products.html
{% extends 'base.html' %}
{% load static %}
{% load humanize %}

{% block content %}

<div class="container py-5">


    <div class="row">



        <div class="col-lg-12">
            <div class="card mb-4" id="tables">
                <div class="card-header text-center">Sản phẩm ưu thích</div>
                {% include 'partials/_messages.html' %}
                <div class="card-body">
                    <table class="table table-hover">
                        <thead>
                            <tr>
                                <th>#</th>
                                <th>Sản phẩm</th>
                                <th>Hình ảnh</th>
                                <th>Giá</th>
                                <th>Danh mục</th>
                                <th> </th>
                            </tr>
                        </thead>
                        <tbody>

                            {% if favorites %}

                            {% for favorite in favorites %}
                            <tr>
                                <td>{{forloop.counter}}</td>       
                                <td><a href="{% url 'store:product-detail' favorite.product.slug %}">{{favorite.product.title}}</a></td>
                                <td>
                                    {% if favorite.product.product_image %}
                                    <a href="{% url 'store:product-detail' favorite.product.slug %}">
                                    <img  src="{{favorite.product.product_image.url}}" alt="{{favorite.product.product_title}}"
                                        style="width:150px;">
                                    </a>
                                    {% endif %}
                                </td>
                                <td>{{favorite.product.price}}đ</td>
                                <td>{{favorite.product.category}}</td>
                                <td class=" border-0"><a class="reset-anchor" href="{% url 'store:remove-like' favorite.id %}"><i class="fas fa-trash-alt small text-muted" ></i></a></td>
                            </tr>
                            {% endfor %}
                            {% endif %}

                        </tbody>
                    </table>

                </div>
            </div>
        </div>

    </div>



</div>
{% endblock content %}

templates/store/orders.html
{% extends 'base.html' %}
{% load static %}
{% load humanize %}

    {% block content %}

      <div class="container py-5">


        <div class="row">

          

          <div class="col-lg-12">
            <div class="card mb-4" id="tables">
              <div class="card-header text-center">Đơn hàng</div>
              <div class="card-body">
                <table class="table table-hover">
                  <thead>
                    <tr>
                      <th>#</th>
                      <th>Sản phẩm</th>
                      <th>Hình ảnh</th>
                      <th>Qty.</th> 
                      <th>Thời gian đặt</th>
                      <th>Trạng thái</th>
                    </tr>
                  </thead>
                  <tbody>

                    {% if orders %}

                      {% for order in orders %}
                        <tr>
                          <td>{{forloop.counter}}</td>
                          <td><a href="{% url 'store:product-detail' order.product.slug %}">{{order.product.title}}</a></td>
                          <td>
                            {% if order.product.product_image %}
                            <a href="{% url 'store:product-detail' order.product.slug %}">
                              <img src="{{order.product.product_image.url}}" alt="{{order.product.product_title}}" style="width:150px;">
                            </a>
                              {% endif %}
                          
                          </td>
                          <td>{{order.quantity}}</td>
                          <td>{{order.ordered_date|naturaltime}}</td>
                          <td>

                            {% if order.status == 'Pending' %}
                            
                            Đang xử lý
                            {% endif %}

                            {% if order.status == 'Accepted' %}
                            <div class="bg-light border border-primary">
                                <div class="p-3 bg-primary" style="width:0;"></div>
                            </div>
                            Đã xác nhận
                            {% endif %}

                            {% if order.status == 'Packed' %}
                            <div class="bg-light border border-primary">
                                <div class="p-3 bg-primary" style="width:40%;"></div>
                            </div>
                            Đã đóng gói
                            {% endif %}
                            
                            
                            {% if order.status == 'On The Way' %}
                            <div class="bg-light border border-primary">
                                <div class="p-3 bg-primary" style="width:70%;"></div>
                            </div>
                            Đã vận chuyển
                            {% endif %}
                            
                            {% if order.status == 'Delivered' %}
                            <div class="bg-light border border-primary">
                                <div class="p-3 bg-primary" style="width:100%;"></div>
                            </div>
                            Đã giao hàng
                            {% endif %}

                            {% if order.status == 'Cancelled' %}
                            <div class="bg-light border border-danger">
                                <div class="p-3 bg-danger" style="width:100%;"></div>
                            </div>
                            Đã huỷ
                            {% endif %}
                            
                            <!-- {{order.status}} -->
                          </td>
                        </tr>
                      {% endfor %}
                    {% endif %}
                    
                  </tbody>
                </table>
                
              </div>
            </div>
          </div>
          
        </div>
    
        
        
      </div>
{% endblock content %}